name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DO_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 170.64.140.205 >> ~/.ssh/known_hosts

    - name: Deploy code to DigitalOcean
      run: |
        rsync -avz --delete ./ root@170.64.140.205:/home/blog/

    - name: Build and restart application
      run: |
        ssh root@170.64.140.205 'cd /home/blog &&
          # 安装依赖（必须保留，确保新代码的依赖都已安装）
          npm install &&

          # 构建应用（必须保留，确保新代码被正确构建）
          npm run build &&

          # 使用PM2重启应用
          pm2 stop tonyiscoding-website || true &&
          pm2 start npm --name "tonyiscoding-website" -- start &&
          pm2 save'
